version: "3.9"

services:
  database:
    container_name: database-service-container
    build:
      context: ./database-service
    ports:
      - "3002:3002"
    volumes:
      - ./database-service:/app

  businesslogic:
    container_name: businesslogic-service-container
    build:
      context: ./businesslogic-service
    ports:
      - "3001:3001"
    volumes:
      - ./businesslogic-service:/app

  file:
    container_name: file-service-container
    build:
      context: ./file-service
    ports:
      - "3003:3003"
    volumes:
      - ./file-service:/app
