version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    container_name: api_container
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: JacobLucky
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
